ol.proj.proj4.register(proj4);
//ol.proj.get("EPSG:4674").setExtent([-39.366804, -12.853901, -38.512871, -12.430966]);
var wms_layers = [];

var format_MunicpiosdaBahia_0 = new ol.format.GeoJSON();
var features_MunicpiosdaBahia_0 = format_MunicpiosdaBahia_0.readFeatures(json_MunicpiosdaBahia_0, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:4674'});
var jsonSource_MunicpiosdaBahia_0 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_MunicpiosdaBahia_0.addFeatures(features_MunicpiosdaBahia_0);
var lyr_MunicpiosdaBahia_0 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_MunicpiosdaBahia_0, 
                style: style_MunicpiosdaBahia_0,
                popuplayertitle: 'Municípios da Bahia  ',
                interactive: true,
                title: '<img src="styles/legend/MunicpiosdaBahia_0.png" /> Municípios da Bahia  '
            });

        var lyr_OSMStandard_1 = new ol.layer.Tile({
            'title': 'OSM Standard',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
            attributions: ' &nbsp &middot; <a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors, CC-BY-SA</a>',
                url: 'http://tile.openstreetmap.org/{z}/{x}/{y}.png'
            })
        });
var format_Cachoeira_2 = new ol.format.GeoJSON();
var features_Cachoeira_2 = format_Cachoeira_2.readFeatures(json_Cachoeira_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:4674'});
var jsonSource_Cachoeira_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Cachoeira_2.addFeatures(features_Cachoeira_2);
var lyr_Cachoeira_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Cachoeira_2, 
                style: style_Cachoeira_2,
                popuplayertitle: ' Cachoeira',
                interactive: true,
                title: '<img src="styles/legend/Cachoeira_2.png" />  Cachoeira'
            });
var format_BaadoIguape_3 = new ol.format.GeoJSON();
var features_BaadoIguape_3 = format_BaadoIguape_3.readFeatures(json_BaadoIguape_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:4674'});
var jsonSource_BaadoIguape_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_BaadoIguape_3.addFeatures(features_BaadoIguape_3);
var lyr_BaadoIguape_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_BaadoIguape_3, 
                style: style_BaadoIguape_3,
                popuplayertitle: 'Baía do Iguape ',
                interactive: true,
                title: '<img src="styles/legend/BaadoIguape_3.png" /> Baía do Iguape '
            });
var format_TerritriosQuilombolaCachoeira_4 = new ol.format.GeoJSON();
var features_TerritriosQuilombolaCachoeira_4 = format_TerritriosQuilombolaCachoeira_4.readFeatures(json_TerritriosQuilombolaCachoeira_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:4674'});
var jsonSource_TerritriosQuilombolaCachoeira_4 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_TerritriosQuilombolaCachoeira_4.addFeatures(features_TerritriosQuilombolaCachoeira_4);
var lyr_TerritriosQuilombolaCachoeira_4 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_TerritriosQuilombolaCachoeira_4, 
                style: style_TerritriosQuilombolaCachoeira_4,
                popuplayertitle: 'Territórios Quilombola Cachoeira',
                interactive: true,
                title: '<img src="styles/legend/TerritriosQuilombolaCachoeira_4.png" /> Territórios Quilombola Cachoeira'
            });

lyr_MunicpiosdaBahia_0.setVisible(true);lyr_OSMStandard_1.setVisible(true);lyr_Cachoeira_2.setVisible(true);lyr_BaadoIguape_3.setVisible(true);lyr_TerritriosQuilombolaCachoeira_4.setVisible(true);
var layersList = [lyr_MunicpiosdaBahia_0,lyr_OSMStandard_1,lyr_Cachoeira_2,lyr_BaadoIguape_3,lyr_TerritriosQuilombolaCachoeira_4];
lyr_MunicpiosdaBahia_0.set('fieldAliases', {'MUNICIPIO': 'MUNICIPIO', 'Codigo': 'Codigo', 'auxiliary_storage_labeling_positionx': 'auxiliary_storage_labeling_positionx', 'auxiliary_storage_labeling_positiony': 'auxiliary_storage_labeling_positiony', 'auxiliary_storage_labeling_lineanchorpercent': 'auxiliary_storage_labeling_lineanchorpercent', 'auxiliary_storage_labeling_lineanchorclipping': 'auxiliary_storage_labeling_lineanchorclipping', 'auxiliary_storage_labeling_lineanchortype': 'auxiliary_storage_labeling_lineanchortype', 'auxiliary_storage_labeling_lineanchortextpoint': 'auxiliary_storage_labeling_lineanchortextpoint', 'auxiliary_storage_labeling_show': 'auxiliary_storage_labeling_show', 'auxiliary_storage_labeling_labelrotation': 'auxiliary_storage_labeling_labelrotation', 'auxiliary_storage_labeling_family': 'auxiliary_storage_labeling_family', 'auxiliary_storage_labeling_fontstyle': 'auxiliary_storage_labeling_fontstyle', 'auxiliary_storage_labeling_size': 'auxiliary_storage_labeling_size', 'auxiliary_storage_labeling_bold': 'auxiliary_storage_labeling_bold', 'auxiliary_storage_labeling_italic': 'auxiliary_storage_labeling_italic', 'auxiliary_storage_labeling_underline': 'auxiliary_storage_labeling_underline', 'auxiliary_storage_labeling_color': 'auxiliary_storage_labeling_color', 'auxiliary_storage_labeling_strikeout': 'auxiliary_storage_labeling_strikeout', 'auxiliary_storage_labeling_multilinealignment': 'auxiliary_storage_labeling_multilinealignment', 'auxiliary_storage_labeling_buffersize': 'auxiliary_storage_labeling_buffersize', 'auxiliary_storage_labeling_buffercolor': 'auxiliary_storage_labeling_buffercolor', 'auxiliary_storage_labeling_bufferdraw': 'auxiliary_storage_labeling_bufferdraw', 'auxiliary_storage_labeling_labeldistance': 'auxiliary_storage_labeling_labeldistance', 'auxiliary_storage_labeling_hali': 'auxiliary_storage_labeling_hali', 'auxiliary_storage_labeling_vali': 'auxiliary_storage_labeling_vali', 'auxiliary_storage_labeling_scalevisibility': 'auxiliary_storage_labeling_scalevisibility', 'auxiliary_storage_labeling_minscale': 'auxiliary_storage_labeling_minscale', 'auxiliary_storage_labeling_maxscale': 'auxiliary_storage_labeling_maxscale', 'auxiliary_storage_labeling_alwaysshow': 'auxiliary_storage_labeling_alwaysshow', 'auxiliary_storage_labeling_calloutdraw': 'auxiliary_storage_labeling_calloutdraw', 'auxiliary_storage_labeling_labelallparts': 'auxiliary_storage_labeling_labelallparts', });
lyr_Cachoeira_2.set('fieldAliases', {'fid': 'fid', 'MUNICIPIO': 'MUNICIPIO', 'Codigo': 'Codigo', 'auxiliary_storage_labeling_positionx': 'auxiliary_storage_labeling_positionx', 'auxiliary_storage_labeling_positiony': 'auxiliary_storage_labeling_positiony', 'auxiliary_storage_labeling_lineanchorpercent': 'auxiliary_storage_labeling_lineanchorpercent', 'auxiliary_storage_labeling_lineanchorclipping': 'auxiliary_storage_labeling_lineanchorclipping', 'auxiliary_storage_labeling_lineanchortype': 'auxiliary_storage_labeling_lineanchortype', 'auxiliary_storage_labeling_lineanchortextpoint': 'auxiliary_storage_labeling_lineanchortextpoint', 'auxiliary_storage_labeling_show': 'auxiliary_storage_labeling_show', });
lyr_BaadoIguape_3.set('fieldAliases', {'gid': 'gid', 'abrev': 'abrev', 'areahaalb': 'areahaalb', 'biomacrl': 'biomacrl', 'biomaibge': 'biomaibge', 'cnuc': 'cnuc', 'criacaoano': 'criacaoano', 'criacaoato': 'criacaoato', 'demarcacao': 'demarcacao', 'escalauc': 'escalauc', 'esferaadm': 'esferaadm', 'fusoabrang': 'fusoabrang', 'gregional': 'gregional', 'grupouc': 'grupouc', 'ngi': 'ngi', 'nomeuc': 'nomeuc', 'perimm': 'perimm', 'siglacateg': 'siglacateg', 'ufabrang': 'ufabrang', 'auxiliary_storage_labeling_positionx': 'auxiliary_storage_labeling_positionx', 'auxiliary_storage_labeling_positiony': 'auxiliary_storage_labeling_positiony', 'auxiliary_storage_labeling_show': 'auxiliary_storage_labeling_show', 'auxiliary_storage_labeling_labelrotation': 'auxiliary_storage_labeling_labelrotation', 'auxiliary_storage_labeling_family': 'auxiliary_storage_labeling_family', 'auxiliary_storage_labeling_fontstyle': 'auxiliary_storage_labeling_fontstyle', 'auxiliary_storage_labeling_size': 'auxiliary_storage_labeling_size', 'auxiliary_storage_labeling_bold': 'auxiliary_storage_labeling_bold', 'auxiliary_storage_labeling_italic': 'auxiliary_storage_labeling_italic', 'auxiliary_storage_labeling_underline': 'auxiliary_storage_labeling_underline', 'auxiliary_storage_labeling_color': 'auxiliary_storage_labeling_color', 'auxiliary_storage_labeling_strikeout': 'auxiliary_storage_labeling_strikeout', 'auxiliary_storage_labeling_multilinealignment': 'auxiliary_storage_labeling_multilinealignment', 'auxiliary_storage_labeling_buffersize': 'auxiliary_storage_labeling_buffersize', 'auxiliary_storage_labeling_buffercolor': 'auxiliary_storage_labeling_buffercolor', 'auxiliary_storage_labeling_bufferdraw': 'auxiliary_storage_labeling_bufferdraw', 'auxiliary_storage_labeling_labeldistance': 'auxiliary_storage_labeling_labeldistance', 'auxiliary_storage_labeling_hali': 'auxiliary_storage_labeling_hali', 'auxiliary_storage_labeling_vali': 'auxiliary_storage_labeling_vali', 'auxiliary_storage_labeling_scalevisibility': 'auxiliary_storage_labeling_scalevisibility', 'auxiliary_storage_labeling_minscale': 'auxiliary_storage_labeling_minscale', 'auxiliary_storage_labeling_maxscale': 'auxiliary_storage_labeling_maxscale', 'auxiliary_storage_labeling_alwaysshow': 'auxiliary_storage_labeling_alwaysshow', 'auxiliary_storage_labeling_calloutdraw': 'auxiliary_storage_labeling_calloutdraw', 'auxiliary_storage_labeling_labelallparts': 'auxiliary_storage_labeling_labelallparts', });
lyr_TerritriosQuilombolaCachoeira_4.set('fieldAliases', {'fid': 'fid', 'gid': 'gid', 'cd_quilomb': 'cd_quilomb', 'cd_sr': 'cd_sr', 'nr_process': 'nr_process', 'nm_comunid': 'nm_comunid', 'nm_municip': 'nm_municip', 'cd_uf': 'cd_uf', 'nr_familia': 'nr_familia', 'ob_descric': 'ob_descric', 'tp_levanta': 'tp_levanta', 'nr_escalao': 'nr_escalao', 'area_calc_': 'area_calc_', 'esfera': 'esfera', 'fase': 'fase', 'responsave': 'responsave', 'auxiliary_storage_labeling_positionx': 'auxiliary_storage_labeling_positionx', 'auxiliary_storage_labeling_positiony': 'auxiliary_storage_labeling_positiony', 'auxiliary_storage_labeling_show': 'auxiliary_storage_labeling_show', 'auxiliary_storage_labeling_labelrotation': 'auxiliary_storage_labeling_labelrotation', 'auxiliary_storage_labeling_family': 'auxiliary_storage_labeling_family', 'auxiliary_storage_labeling_fontstyle': 'auxiliary_storage_labeling_fontstyle', 'auxiliary_storage_labeling_size': 'auxiliary_storage_labeling_size', 'auxiliary_storage_labeling_bold': 'auxiliary_storage_labeling_bold', 'auxiliary_storage_labeling_italic': 'auxiliary_storage_labeling_italic', 'auxiliary_storage_labeling_underline': 'auxiliary_storage_labeling_underline', 'auxiliary_storage_labeling_color': 'auxiliary_storage_labeling_color', 'auxiliary_storage_labeling_strikeout': 'auxiliary_storage_labeling_strikeout', 'auxiliary_storage_labeling_multilinealignment': 'auxiliary_storage_labeling_multilinealignment', 'auxiliary_storage_labeling_buffersize': 'auxiliary_storage_labeling_buffersize', 'auxiliary_storage_labeling_buffercolor': 'auxiliary_storage_labeling_buffercolor', 'auxiliary_storage_labeling_bufferdraw': 'auxiliary_storage_labeling_bufferdraw', 'auxiliary_storage_labeling_labeldistance': 'auxiliary_storage_labeling_labeldistance', 'auxiliary_storage_labeling_hali': 'auxiliary_storage_labeling_hali', 'auxiliary_storage_labeling_vali': 'auxiliary_storage_labeling_vali', 'auxiliary_storage_labeling_scalevisibility': 'auxiliary_storage_labeling_scalevisibility', 'auxiliary_storage_labeling_minscale': 'auxiliary_storage_labeling_minscale', 'auxiliary_storage_labeling_maxscale': 'auxiliary_storage_labeling_maxscale', 'auxiliary_storage_labeling_alwaysshow': 'auxiliary_storage_labeling_alwaysshow', 'auxiliary_storage_labeling_calloutdraw': 'auxiliary_storage_labeling_calloutdraw', 'auxiliary_storage_labeling_labelallparts': 'auxiliary_storage_labeling_labelallparts', });
lyr_MunicpiosdaBahia_0.set('fieldImages', {'MUNICIPIO': 'TextEdit', 'Codigo': 'TextEdit', 'auxiliary_storage_labeling_positionx': 'Hidden', 'auxiliary_storage_labeling_positiony': 'Hidden', 'auxiliary_storage_labeling_lineanchorpercent': '', 'auxiliary_storage_labeling_lineanchorclipping': '', 'auxiliary_storage_labeling_lineanchortype': '', 'auxiliary_storage_labeling_lineanchortextpoint': '', 'auxiliary_storage_labeling_show': 'Hidden', 'auxiliary_storage_labeling_labelrotation': 'Hidden', 'auxiliary_storage_labeling_family': 'Hidden', 'auxiliary_storage_labeling_fontstyle': 'Hidden', 'auxiliary_storage_labeling_size': 'Hidden', 'auxiliary_storage_labeling_bold': 'Hidden', 'auxiliary_storage_labeling_italic': 'Hidden', 'auxiliary_storage_labeling_underline': 'Hidden', 'auxiliary_storage_labeling_color': 'Hidden', 'auxiliary_storage_labeling_strikeout': 'Hidden', 'auxiliary_storage_labeling_multilinealignment': 'Hidden', 'auxiliary_storage_labeling_buffersize': 'Hidden', 'auxiliary_storage_labeling_buffercolor': 'Hidden', 'auxiliary_storage_labeling_bufferdraw': 'Hidden', 'auxiliary_storage_labeling_labeldistance': 'Hidden', 'auxiliary_storage_labeling_hali': 'Hidden', 'auxiliary_storage_labeling_vali': 'Hidden', 'auxiliary_storage_labeling_scalevisibility': 'Hidden', 'auxiliary_storage_labeling_minscale': 'Hidden', 'auxiliary_storage_labeling_maxscale': 'Hidden', 'auxiliary_storage_labeling_alwaysshow': 'Hidden', 'auxiliary_storage_labeling_calloutdraw': 'Hidden', 'auxiliary_storage_labeling_labelallparts': 'Hidden', });
lyr_Cachoeira_2.set('fieldImages', {'fid': 'TextEdit', 'MUNICIPIO': 'TextEdit', 'Codigo': 'TextEdit', 'auxiliary_storage_labeling_positionx': 'Hidden', 'auxiliary_storage_labeling_positiony': 'Hidden', 'auxiliary_storage_labeling_lineanchorpercent': 'TextEdit', 'auxiliary_storage_labeling_lineanchorclipping': 'TextEdit', 'auxiliary_storage_labeling_lineanchortype': 'TextEdit', 'auxiliary_storage_labeling_lineanchortextpoint': 'TextEdit', 'auxiliary_storage_labeling_show': 'Hidden', });
lyr_BaadoIguape_3.set('fieldImages', {'gid': 'Range', 'abrev': 'TextEdit', 'areahaalb': 'TextEdit', 'biomacrl': 'TextEdit', 'biomaibge': 'TextEdit', 'cnuc': 'TextEdit', 'criacaoano': 'TextEdit', 'criacaoato': 'TextEdit', 'demarcacao': 'TextEdit', 'escalauc': 'TextEdit', 'esferaadm': 'TextEdit', 'fusoabrang': 'TextEdit', 'gregional': 'TextEdit', 'grupouc': 'TextEdit', 'ngi': 'TextEdit', 'nomeuc': 'TextEdit', 'perimm': 'TextEdit', 'siglacateg': 'TextEdit', 'ufabrang': 'TextEdit', 'auxiliary_storage_labeling_positionx': 'Hidden', 'auxiliary_storage_labeling_positiony': 'Hidden', 'auxiliary_storage_labeling_show': 'Hidden', 'auxiliary_storage_labeling_labelrotation': 'Hidden', 'auxiliary_storage_labeling_family': 'Hidden', 'auxiliary_storage_labeling_fontstyle': 'Hidden', 'auxiliary_storage_labeling_size': 'Hidden', 'auxiliary_storage_labeling_bold': 'Hidden', 'auxiliary_storage_labeling_italic': 'Hidden', 'auxiliary_storage_labeling_underline': 'Hidden', 'auxiliary_storage_labeling_color': 'Hidden', 'auxiliary_storage_labeling_strikeout': 'Hidden', 'auxiliary_storage_labeling_multilinealignment': 'Hidden', 'auxiliary_storage_labeling_buffersize': 'Hidden', 'auxiliary_storage_labeling_buffercolor': 'Hidden', 'auxiliary_storage_labeling_bufferdraw': 'Hidden', 'auxiliary_storage_labeling_labeldistance': 'Hidden', 'auxiliary_storage_labeling_hali': 'Hidden', 'auxiliary_storage_labeling_vali': 'Hidden', 'auxiliary_storage_labeling_scalevisibility': 'Hidden', 'auxiliary_storage_labeling_minscale': 'Hidden', 'auxiliary_storage_labeling_maxscale': 'Hidden', 'auxiliary_storage_labeling_alwaysshow': 'Hidden', 'auxiliary_storage_labeling_calloutdraw': 'Hidden', 'auxiliary_storage_labeling_labelallparts': 'Hidden', });
lyr_TerritriosQuilombolaCachoeira_4.set('fieldImages', {'fid': 'TextEdit', 'gid': 'Range', 'cd_quilomb': 'Range', 'cd_sr': 'TextEdit', 'nr_process': 'TextEdit', 'nm_comunid': 'TextEdit', 'nm_municip': 'TextEdit', 'cd_uf': 'TextEdit', 'nr_familia': 'Range', 'ob_descric': 'TextEdit', 'tp_levanta': 'TextEdit', 'nr_escalao': 'TextEdit', 'area_calc_': 'TextEdit', 'esfera': 'TextEdit', 'fase': 'TextEdit', 'responsave': 'TextEdit', 'auxiliary_storage_labeling_positionx': 'Hidden', 'auxiliary_storage_labeling_positiony': 'Hidden', 'auxiliary_storage_labeling_show': 'Hidden', 'auxiliary_storage_labeling_labelrotation': 'Hidden', 'auxiliary_storage_labeling_family': 'Hidden', 'auxiliary_storage_labeling_fontstyle': 'Hidden', 'auxiliary_storage_labeling_size': 'Hidden', 'auxiliary_storage_labeling_bold': 'Hidden', 'auxiliary_storage_labeling_italic': 'Hidden', 'auxiliary_storage_labeling_underline': 'Hidden', 'auxiliary_storage_labeling_color': 'Hidden', 'auxiliary_storage_labeling_strikeout': 'Hidden', 'auxiliary_storage_labeling_multilinealignment': 'Hidden', 'auxiliary_storage_labeling_buffersize': 'Hidden', 'auxiliary_storage_labeling_buffercolor': 'Hidden', 'auxiliary_storage_labeling_bufferdraw': 'Hidden', 'auxiliary_storage_labeling_labeldistance': 'Hidden', 'auxiliary_storage_labeling_hali': 'Hidden', 'auxiliary_storage_labeling_vali': 'Hidden', 'auxiliary_storage_labeling_scalevisibility': 'Hidden', 'auxiliary_storage_labeling_minscale': 'Hidden', 'auxiliary_storage_labeling_maxscale': 'Hidden', 'auxiliary_storage_labeling_alwaysshow': 'Hidden', 'auxiliary_storage_labeling_calloutdraw': 'Hidden', 'auxiliary_storage_labeling_labelallparts': 'Hidden', });
lyr_MunicpiosdaBahia_0.set('fieldLabels', {'MUNICIPIO': 'no label', 'Codigo': 'no label', 'auxiliary_storage_labeling_lineanchorpercent': 'no label', 'auxiliary_storage_labeling_lineanchorclipping': 'no label', 'auxiliary_storage_labeling_lineanchortype': 'no label', 'auxiliary_storage_labeling_lineanchortextpoint': 'no label', });
lyr_Cachoeira_2.set('fieldLabels', {'fid': 'no label', 'MUNICIPIO': 'no label', 'Codigo': 'no label', 'auxiliary_storage_labeling_lineanchorpercent': 'no label', 'auxiliary_storage_labeling_lineanchorclipping': 'no label', 'auxiliary_storage_labeling_lineanchortype': 'no label', 'auxiliary_storage_labeling_lineanchortextpoint': 'no label', });
lyr_BaadoIguape_3.set('fieldLabels', {'gid': 'no label', 'abrev': 'no label', 'areahaalb': 'no label', 'biomacrl': 'no label', 'biomaibge': 'no label', 'cnuc': 'no label', 'criacaoano': 'no label', 'criacaoato': 'no label', 'demarcacao': 'no label', 'escalauc': 'no label', 'esferaadm': 'no label', 'fusoabrang': 'no label', 'gregional': 'no label', 'grupouc': 'no label', 'ngi': 'no label', 'nomeuc': 'no label', 'perimm': 'no label', 'siglacateg': 'no label', 'ufabrang': 'no label', });
lyr_TerritriosQuilombolaCachoeira_4.set('fieldLabels', {'fid': 'no label', 'gid': 'no label', 'cd_quilomb': 'no label', 'cd_sr': 'no label', 'nr_process': 'no label', 'nm_comunid': 'no label', 'nm_municip': 'no label', 'cd_uf': 'no label', 'nr_familia': 'no label', 'ob_descric': 'no label', 'tp_levanta': 'no label', 'nr_escalao': 'no label', 'area_calc_': 'no label', 'esfera': 'no label', 'fase': 'no label', 'responsave': 'no label', });
lyr_TerritriosQuilombolaCachoeira_4.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});